# Generated by Django 3.1.4 on 2021-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='a',
            field=models.CharField(default='', max_length=10),
        ),
    ]
