# Generated by Django 3.1.4 on 2021-01-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='a',
        ),
    ]
