# Generated by Django 3.1.4 on 2021-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guides',
            name='caution',
            field=models.CharField(max_length=500, null='True', verbose_name='Caution'),
        ),
        migrations.AlterField(
            model_name='guides',
            name='side_effect',
            field=models.CharField(max_length=500, null='True', verbose_name='Side-Effect'),
        ),
    ]
