# Generated by Django 3.1.6 on 2021-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20210203_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='guides',
            name='symptoms',
            field=models.CharField(max_length=1000, null='False'),
            preserve_default='False',
        ),
    ]
