# Generated by Django 2.1.5 on 2021-03-24 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SK_Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_price', models.FloatField(default=0.0)),
                ('pd_qty', models.IntegerField(default=0)),
                ('pd_tot', models.FloatField(default=0.0)),
                ('date_data', models.DateField(blank=True, null=True)),
                ('store_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.Medicine')),
            ],
        ),
    ]
