# Generated by Django 3.1.7 on 2021-03-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_guides_diseases'),
        ('pred', '0002_auto_20210325_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_price', models.FloatField(default=0.0)),
                ('pd_qty', models.IntegerField(default=0)),
                ('pd_tot', models.FloatField(default=0.0)),
                ('date_data', models.DateField(blank=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.guides')),
            ],
        ),
        migrations.DeleteModel(
            name='SK_Bills',
        ),
    ]
