# Generated by Django 3.1.7 on 2021-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0005_auto_20210325_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='date_data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
