# Generated by Django 3.1.7 on 2021-03-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_guides_diseases'),
        ('pred', '0007_auto_20210325_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='date_data',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.guides', verbose_name='Medicine'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pd_price',
            field=models.FloatField(default=0.0, verbose_name='Medicine Price'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pd_qty',
            field=models.IntegerField(default=0, verbose_name='Medicine Quantity'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pd_tot',
            field=models.FloatField(default=0.0, verbose_name='Total price'),
        ),
    ]
