# Generated by Django 3.1.7 on 2021-04-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0008_auto_20210325_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='date_data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
