# Generated by Django 3.1.6 on 2021-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0009_auto_20210413_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='date_data',
            field=models.DateField(default='', max_length=100),
        ),
    ]
