# Generated by Django 3.1.6 on 2021-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Master', '0003_auto_20210211_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='forgot_pass',
            field=models.CharField(default='', max_length=100, verbose_name='Write your password hint'),
        ),
    ]
