# Generated by Django 3.1.7 on 2021-03-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Master', '0004_userregister_forgot_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
