# Generated by Django 3.1.6 on 2021-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Master', '0005_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='useraddress',
            field=models.CharField(default='', max_length=200, verbose_name='Address'),
        ),
    ]
