# Generated by Django 2.1.5 on 2021-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catn', models.CharField(max_length=80)),
                ('dhmail', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(max_length=80)),
                ('cohmail', models.CharField(max_length=80)),
                ('copmail', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='inc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'open'), ('2', 'close')], default=1, max_length=80)),
                ('incdes', models.CharField(max_length=80)),
                ('buildname', models.CharField(max_length=80)),
                ('wardname', models.CharField(max_length=80)),
                ('roomname', models.CharField(max_length=80)),
                ('bedname', models.CharField(max_length=10)),
                ('catname', models.CharField(max_length=80)),
                ('opname', models.CharField(max_length=80)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
    ]
