# Generated by Django 2.1.5 on 2021-03-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inc',
            name='endcomment',
            field=models.CharField(default='no', max_length=80),
        ),
        migrations.AlterField(
            model_name='inc',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('close', 'close')], default='open', max_length=80),
        ),
    ]
