# Generated by Django 3.1.7 on 2021-03-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210324_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inc',
            name='endcomment',
        ),
        migrations.RemoveField(
            model_name='inc',
            name='status',
        ),
    ]
