# Generated by Django 3.1.7 on 2021-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20210326_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inc',
            name='bedname',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='inc',
            name='buildname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='inc',
            name='catname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='inc',
            name='incdes',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='inc',
            name='opname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='inc',
            name='roomname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='inc',
            name='wardname',
            field=models.CharField(default='', max_length=80),
        ),
    ]
