# Generated by Django 3.1.7 on 2021-03-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20210326_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inc',
            name='opname',
            field=models.EmailField(default='', max_length=80),
        ),
    ]
