# Generated by Django 3.1.7 on 2021-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20210326_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inc',
            name='incdes',
            field=models.CharField(default='', max_length=800),
        ),
    ]
