# Generated by Django 3.1.4 on 2021-01-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_fname', models.CharField(max_length=50)),
                ('doc_mname', models.CharField(max_length=50)),
                ('doc_lname', models.CharField(max_length=50)),
                ('doc_email', models.EmailField(max_length=100, unique=True)),
                ('doc_dob', models.DateField()),
                ('doc_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('doc_address', models.TextField(max_length=200)),
                ('doc_city', models.CharField(max_length=50)),
                ('doc_pcode', models.IntegerField(max_length=6)),
                ('doc_mob', models.IntegerField(max_length=10)),
                ('doc_avatar', models.FileField(upload_to='upload', verbose_name='store image')),
            ],
        ),
    ]
