# Generated by Django 3.1.4 on 2021-01-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_mob',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_pcode',
            field=models.IntegerField(default=''),
        ),
    ]
