# Generated by Django 3.1.4 on 2021-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20210106_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_fname', models.CharField(max_length=50)),
                ('pat_mname', models.CharField(max_length=50)),
                ('pat_lname', models.CharField(max_length=50)),
                ('pat_email', models.EmailField(max_length=100, unique=True)),
                ('pat_dob', models.DateField(default='')),
                ('pat_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('pat_address', models.TextField(max_length=200)),
                ('pat_city', models.CharField(max_length=50)),
                ('pat_pcode', models.IntegerField(default='')),
                ('pat_mob', models.IntegerField(default='')),
            ],
        ),
    ]
