# Generated by Django 3.1.4 on 2021-01-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='adminapp',
        ),
    ]
