# Generated by Django 3.1.4 on 2021-01-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_auto_20210106_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='doc_avatar',
        ),
    ]
