# Generated by Django 3.1.4 on 2021-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_remove_doctors_doc_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pat_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
