# Generated by Django 3.1.4 on 2021-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_auto_20210108_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pat_dob',
            field=models.CharField(default='', max_length=15),
        ),
    ]
