# Generated by Django 3.1.4 on 2021-01-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_auto_20210108_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_dep',
            field=models.CharField(default='', max_length=50),
        ),
    ]
