# Generated by Django 3.1.4 on 2021-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0009_doctors_doc_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
