# Generated by Django 3.1.4 on 2021-02-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0012_auto_20210109_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_dep',
            field=models.CharField(choices=[('Allergists', 'Allergists'), ('Anesthesiologists', 'Anesthesiologists'), ('Cardiologists', 'Cardiologists'), ('Dermatologists', 'Dermatologists'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Critical Care Medicine Specialists', 'Critical Care Medicine Specialists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists')], default='', max_length=1000),
        ),
    ]
