# Generated by Django 3.1.6 on 2021-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0013_auto_20210203_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminapp',
            name='forgot_pass',
            field=models.CharField(default='', max_length=100, verbose_name='Write your password hint'),
        ),
    ]
