# Generated by Django 3.1.7 on 2021-03-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0016_auto_20210316_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_department',
            name='doc_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
