# Generated by Django 3.1.7 on 2021-03-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0018_auto_20210316_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_department',
            name='end_time',
            field=models.TimeField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor_department',
            name='start_time',
            field=models.TimeField(default='', max_length=50),
        ),
    ]
