# Generated by Django 3.1.7 on 2021-03-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0020_auto_20210316_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_department',
            old_name='end_time',
            new_name='available_time',
        ),
        migrations.RemoveField(
            model_name='doctor_department',
            name='start_time',
        ),
    ]
