# Generated by Django 3.1.7 on 2021-03-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0023_doctor_department_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_department',
            name='doc_dept',
            field=models.CharField(default='', max_length=100),
        ),
    ]
