# Generated by Django 3.1.6 on 2021-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0024_doctor_department_doc_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pat_des',
            field=models.TextField(default='', max_length=800),
        ),
    ]
