# Generated by Django 3.1.6 on 2021-03-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0025_patient_pat_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pat_des',
        ),
    ]
