# Generated by Django 3.1.6 on 2021-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemist_Master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistregister',
            name='forgot_pass',
            field=models.CharField(default='', max_length=100, verbose_name='Write your password hint'),
        ),
    ]
